# Generated by Django 2.1.3 on 2018-11-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_site_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
