# Generated by Django 2.1.3 on 2018-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181112_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.CharField(blank=True, max_length=1024)),
                ('urlPartBeforeKeywords', models.CharField(max_length=1024)),
                ('urlPartAfterKeywords', models.CharField(max_length=1024)),
            ],
        ),
    ]
